cp   = 1004.       # specific heat (constant P) [J kg-1 K-1]
g    = 9.8         # grav acceleration []
tref = 295.        # reference temperature [K]
rho  = 1.2         # density [kg m-3]
Rd   = 287.06      # gas constant dry air
Rv   = 461.5       # gas constant moits air
Lv   = 2.45e6      # Latent heat of vaporization
kappa = 0.4        # Von Karman constant
m2k = 1.95         # convert m/s to kts 
eps = 1.e-12       # small number 
filval = -9999     # Fill value for missing data
